# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

originate_intercept_cpp <- function(r, parameters) {
    .Call('_predictr_originate_intercept_cpp', PACKAGE = 'predictr', r, parameters)
}

accumulate_linear_cpp <- function(m, parameters, v) {
    .Call('_predictr_accumulate_linear_cpp', PACKAGE = 'predictr', m, parameters, v)
}

